### ISSUE TITLE
recall the meaning of RDF-T

### ISSUE THREAD

**Issue by JBPressac** [w3c/sparql-query#137]
Hello,

In section 18.1.2 Query Variables, wouldn't the following sentence be more comprehensible if the meaning of RDF-T (RDF Terms) were indicated in brackets?

> A query variable is a member of the set V where V is infinite and disjoint from RDF-T.

Suggestion:

> A query variable is a member of the set V where V is infinite and disjoint from RDF-T (RDF terms).

Thanks,

**Comment by hartig** [comment]
Thanks for the suggestion @JBPressac ! Excellent point. In fact, instead of simply mentioning in parenthesis what RDF-T is, I would prefer to to make (every use of) RDF-T a link to points to its definition.

Yet, looking at our [current draft for version 1.2 of the spec](https://w3c.github.io/sparql-query/spec/), I wonder were this definition actually is. Version 1.1 has it in [Section 18.1.1 RDF Terms](https://www.w3.org/TR/sparql11-query/#sparqlBasicTerms), but there is no such section anymore in version 1.2 (now, [Section 18.1.1](https://w3c.github.io/sparql-query/spec/#sparqlDataset) is about RDF datasets). @afs, I assume the section was removed in the context of saying that the notion of RDF term is defined in RDF Concepts and doesn't need to be redefined here, right?

I will create a PR to fix these issues.

**Comment by hartig** [comment]
I have created PR #138 to address this issue (and similar issues in some of the other definitions in Section 18.1). You can look at the following preview in which the changes of the PR are applied:
https://pr-preview.s3.amazonaws.com/w3c/sparql-query/pull/138.html#sparqlQueryVariables

**Comment by afs** [comment]
@hartig - yes - the spec can link to RDF Concepts 1.2 now the two specs are being managed in a combined fashion.

History: "RDF Term" came in at SPARQL 1.0 as there was no aduquate RDF terminology equivalent. SPARQL 1.1 was formally before RDF 1.1 even though the intent was to align.  Specs could not link to non-specs for normative definitions.

**Comment by JBPressac** [comment]
Thank you for this clarification
