### ISSUE TITLE
What about XPath dependency: 2.0 vs 3.0

### ISSUE THREAD

**Issue by Tpt** [w3c/sparql-query#86]
Currently the specification text refers to XPath 2.0 in its text but links to the latest version (3.1). We should fix that and either explicitely link to 2.0 or make the decision to upgrade the specification to 3.0.

<s>I believe the major difference between XPath 2 and 3 impacting SPARQL is the introduction by XPath 3 of an "implicit timezone" such that calendar values with and without timezone are now compatible together using this implicit timezone.</s>

Following this change in SPARQL 1.2 is I believe ok (it only makes expressions that were returning and error pass and this kind of change is explicitely allowed as backward compatible by SPARQL) but it's a signficiant change.

**Comment by afs** [comment]
It's good to have this issue. Somewhere, we need to add text about the issue.

The use of implicit timezone is part of [XQuery 1.0 and XPath 2.0 Functions and Operators (2007)](https://www.w3.org/TR/2007/REC-xpath-functions-20070123/#comp.duration.datetime) as well.

In the RDF context, where data is on the web and can be drawn from multiple sources, there isn't a natural timezone, nor will it be the same as the request origin. Even a single data source, data collected over time, is affected because of DST.

For SPARQL, it is useful for sorting because it gives a total order.

For comparisons, the implicit timezone is less useful. RDF Concepts refers to XML Schema 1.1. The [indeterminate comparison order](https://www.w3.org/TR/xmlschema11-2/#dateTime) at least does not give false information. I don't see much use of [xsd:dateTimeStamp](https://www.w3.org/TR/xmlschema11-2/#dateTimeStamp).

We could choose to say that there is no implicit timezone by default for comparison (i.e. XML Schema rules) and suggest its use for ordering. Maybe also say implementations _MAY_ (RFC 2119) provide an implicit timezone with certain consequences.

We'd need text about this and it is shame not to be able to just refer to F&O but overall I think it's worth it.

If instead we choose to have a timezone, there ought to be only one. `+00:00` (c.f. cloud provide server clocks.) for same answers everywhere.

Another XML Schema 1.0 - XML Scheme 1.1 change is that year 0 represents 1 BCE in 1.1 :: https://www.w3.org/TR/xmlschema11-2/#dateTime-value-space

**Comment by Tpt** [comment]
I believe we can close this issue. We upgrade references to XPath 3.1 in #89

**Comment by afs** [comment]
#88 records the need to document the change that year 0 represents 1 BCE in 1.1.

I've created issue #116 about the implicit timezone. (We may decide to do nothing but it is better to know that is the case, rather than adopt it as a effect of using F&O 3.0.
