### ISSUE TITLE
Consider dropping "set union" requirement of CONSTRUCT output

### ISSUE THREAD

**Issue by Tpt** [w3c/sparql-query#91]
Currently [the CONSTRUCT specification states](https://www.w3.org/TR/sparql11-query/#construct)  that <q>The [CONSTRUCT query] result is an RDF graph formed by taking each query solution in the solution sequence [...] and combining the triples into a single RDF graph by set union.</q>. Hence, it suggests that the triples emitted by CONSTRUCT queries should be deduplicated.

According to w3c/sparql-12/issues/86 it seems that it is not the approach taken by a lot implementations. It might be relevant to lift this requirement.

**Comment by afs** [comment]
Agreed. in https://github.com/w3c/sparql-12/issues/86 this is, arguably, an errata though deduplication is not strictly there.

The "set union" is a mechanism to achieve an effect. An RDF graph has to appear to be a set of triples. 
As the spec result is an HTTP response in an RDF syntax, the burden can be moved to the client.

The spec does not cover APIs.

The text is also saying the combining operation is not graph merge.

What does need to be said is the result is all the triples from all the template instantiations are included, not other triples out of thin air, and respecting the blank nodes. The cardinality is at least one but is not otherwise prescribed.

Maybe the text could say "multiset union" which would put an upper bound on cardinality as well.
Or include text saying duplicates may still be present.

**Comment by hartig** [comment]
I agree with dropping the set-union requirement. However, given that we do, I would then like to see a 'Note' with a brief explanation of why there is no such requirement. I think such a note would be helpful for future readers of our spec who might think that this should be a natural thing to require and, then, wonder why there is no such requirement.

**Comment by kasei** [comment]
Agreed a note would be a good idea here.

I don't actually think there's any change required to the normative text, though. The result being a "graph" means that the formation is necessarily by set union. That doesn't really have anything to do with the serialization of that graph into a concrete syntax where each triple might appear more than once. For that reason, I think I'd be opposed to language like "multisite union" that implied that having *too many* repeated triples in the serialization was somehow an error (inadvisable, sure, but perfectly fine).

**Comment by Tpt** [comment]
Thank you for your replies! I have opened #93 that adds a note clarifying that building the graph by "set union" does not enforces triples deduplication on the syntax level.

**Comment by Tpt** [comment]
#93 is now merged.
